# Generated by Django 5.0.6 on 2024-07-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
