# Generated by Django 5.0.6 on 2024-07-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size1',
            field=models.ManyToManyField(blank=True, null=True, to='my_app.size'),
        ),
    ]
