# Generated by Django 5.0.6 on 2024-07-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color1',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='my_app.color'),
        ),
    ]
