# Generated by Django 5.0.6 on 2024-07-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_add_to_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_to_cart',
        ),
    ]
