# Generated by Django 5.0.6 on 2024-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
