# Generated by Django 5.0.6 on 2024-07-31 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_addtocart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='color_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.color'),
        ),
    ]
