# Generated by Django 5.0.6 on 2024-07-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_addtocart_color_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
