# Generated by Django 5.0.6 on 2024-08-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_code',
            name='one_time_use',
            field=models.BooleanField(default=True),
        ),
    ]
