# Generated by Django 5.0.6 on 2024-08-06 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_billing_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('order_id', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=60, null=True)),
                ('quantity', models.CharField(blank=True, max_length=60, null=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], max_length=60, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('address_id', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.address')),
                ('user_id', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.user')),
            ],
        ),
    ]
