# Generated by Django 5.0.6 on 2024-08-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_rename_address_address_address1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
