# Generated by Django 5.0.6 on 2024-08-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='size',
            new_name='size_order',
        ),
    ]
