# Generated by Django 5.0.6 on 2024-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_user_dob_user_gender_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
