# Generated by Django 5.0.6 on 2024-09-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0037_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='half_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
