# Generated by Django 5.0.6 on 2024-09-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0038_products_half_rating_products_rating1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('rating_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.rating')),
            ],
        ),
    ]
