# Generated by Django 5.0.6 on 2024-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0039_review_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_like',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review_like',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
