# Generated by Django 5.0.6 on 2024-12-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0040_alter_review_like_dislike_alter_review_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_code',
            name='user_id',
            field=models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
    ]
