# Generated by Django 5.0.6 on 2024-12-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0042_remove_coupon_code_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
