# Generated by Django 5.0.6 on 2024-12-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0043_addtocart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='discount',
        ),
    ]
