# Generated by Django 5.0.6 on 2024-12-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0045_user_coupon_ex'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_code',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
