# Generated by Django 5.0.6 on 2024-12-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0046_coupon_code_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_coupon',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
